/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    CheckBox: typeof import('./src/components/CheckBox.vue')['default']
    DynamicForm: typeof import('./src/components/DynamicForm.vue')['default']
    ErrorBox: typeof import('./src/components/ErrorBox.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    InputBox: typeof import('./src/components/InputBox.vue')['default']
    MemorySelect: typeof import('./src/components/MemorySelect.vue')['default']
    MessageBox: typeof import('./src/components/MessageBox.vue')['default']
    ModalBox: typeof import('./src/components/ModalBox.vue')['default']
    NotificationStack: typeof import('./src/components/NotificationStack.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectBox: typeof import('./src/components/SelectBox.vue')['default']
    SidePanel: typeof import('./src/components/SidePanel.vue')['default']
    ThemeButton: typeof import('./src/components/ThemeButton.vue')['default']
  }
}
